name       : osinfo-db-tools
version    : 1.1.0
release    : 1
source     :
    - https://releases.pagure.org/libosinfo/osinfo-db-tools-1.1.0.tar.gz : a141cd2fc07c30d84801b5dbf6b11f2c2e708b0e81216277d052ac0b57fe546b
license    : GPL-2.0
component  : programming.tools
summary    : Tools for manipulating osinfo database
description: |
    Tools for manipulating osinfo database
builddeps  :
    - pkgconfig(libxml-2.0)
    - pkgconfig(libxslt)
    - pkgconfig(libarchive)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
