name       : osinfo-db-tools
version    : 1.2.0
release    : 3
source     :
    - https://gitlab.com/libosinfo/osinfo-db-tools/-/archive/v1.2.0/osinfo-db-tools-v1.2.0.tar.gz : 3376657eeff71f111d87ef0d724ec954ea72f2f6b06b84c7bd6604ed5740571e
license    : GPL-2.0-or-later
component  : programming.tools
summary    : Tools for manipulating osinfo database
description: |
    Tools for manipulating osinfo database
builddeps  :
    - pkgconfig(libxml-2.0)
    - pkgconfig(libxslt)
    - pkgconfig(libarchive)
    - gnome-common
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
