name       : osinfo-db-tools
version    : 1.7.0
release    : 4
source     :
    - https://gitlab.com/libosinfo/osinfo-db-tools/-/archive/v1.7.0/osinfo-db-tools-v1.7.0.tar.gz : b4212a790a2f4c0de24b4e0791a861f31e283ac93107fdcac8c8f04e5dc3a683
license    : GPL-2.0-or-later
component  : programming.tools
summary    : Tools for manipulating osinfo database
description: |
    Tools for manipulating osinfo database
builddeps  :
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libarchive)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libxslt)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
