name       : osinfo-db-tools
version    : 2.1.0
release    : 2
source     :
    - https://gitlab.com/libosinfo/osinfo-db-tools/-/archive/v1.1.0/osinfo-db-tools-v1.1.0.tar.gz : ba817387f23f940a93454e493eb76fc7873b323eee76961a312de008b97348a2
license    : GPL-2.0-or-later
component  : programming.tools
summary    : Tools for manipulating osinfo database
description: |
    Tools for manipulating osinfo database
builddeps  :
    - pkgconfig(libxml-2.0)
    - pkgconfig(libxslt)
    - pkgconfig(libarchive)
    - gnome-common
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
