name       : osinfo-db-tools
version    : 1.9.0
release    : 6
source     :
    - https://gitlab.com/libosinfo/osinfo-db-tools/-/archive/v1.9.0/osinfo-db-tools-v1.9.0.tar.gz : f6642759dbd5632a53029dfb710d347d46d4acaf256258c39fd301077c40d6f1
license    : GPL-2.0-or-later
component  : programming.tools
summary    : Tools for manipulating osinfo database
description: |
    Tools for manipulating osinfo database
builddeps  :
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libarchive)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(libxslt)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
